name: Build devkitPro examples

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-nds-3ds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Install and update packages
        run: |
          apt-get -y install python3 python3-pip p7zip-full libarchive13
          python3 --version
          python3 -m pip install --upgrade pip setuptools

      - name: Clone and compile nds-examples
        run: |
          git clone --recursive https://github.com/devkitPro/nds-examples nds-examples
          find nds-examples -type f -name Makefile -execdir make \;

      - name: Clone and compile 3ds-examples
        run: |
          git clone --recursive https://github.com/devkitPro/3ds-examples 3ds-examples
          find 3ds-examples -type f -name Makefile -execdir make \;

      - name: Upload NDS binaries
        uses: actions/upload-artifact@v4
        with:
          name: Source & Binaries (NDS)
          path: nds-examples

      - name: Upload 3DS binaries
        uses: actions/upload-artifact@v4
        with:
          name: Source & Binaries (3DS)
          path: 3ds-examples

  build-gc-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc

    steps:
      - uses: actions/checkout@v4

      - name: Install and update packages
        run: |
          apt-get -y install python3 python3-pip p7zip-full libarchive13
          python3 --version
          python3 -m pip install --upgrade pip setuptools

      - name: Clone and compile gamecube-examples
        run: |
          git clone --recursive https://github.com/devkitPro/gamecube-examples gamecube-examples
          find gamecube-examples -type f -name Makefile -execdir make \;
    
      - name: Clone and compile wii-examples
        run: |
          git clone --recursive https://github.com/devkitPro/wii-examples wii-examples
          find wii-examples -type f -name Makefile -execdir make \;

      - name: Upload GameCube binaries
        uses: actions/upload-artifact@v4
        with:
          name: Source & Binaries (GameCube)
          path: gamecube-examples

      - name: Upload Wii binaries
        uses: actions/upload-artifact@v4
        with:
          name: Source & Binaries (Wii)
          path: wii-examples
        
